FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/monitoring /app/app/monitoring
COPY src /app/src

CMD ["uvicorn", "app.monitoring.service:app", "--host", "0.0.0.0", "--port", "8082"]
