FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ui /app/app/ui

CMD ["streamlit", "run", "app/ui/streamlit_app.py", "--server.port", "8081", "--server.address", "0.0.0.0"]
